---
- name: Install kibana deb from a yandex mirror
  apt:
    deb: "https://mirror.yandex.ru/mirrors/elastic/{{ elk_major_version }}/pool/main/k/kibana/kibana-{{ elk_version }}-amd64.deb"

- name: Template Kibana
  template:
    src: /home/user/ansible/kibana.j2
    dest: /etc/kibana/kibana.yml
    mode: 0644
  notify:
    - Restart Kibana
