---
- name: Install kibana deb from a yandex mirror
  apt:
    deb: "https://mirror.yandex.ru/mirrors/elastic/{{ elk_major_version }}/pool/main/k/kibana/kibana-{{ elk_version }}.deb"
  notify:
    - Restart Kibana
  when: ansible_host in groups['kibana']
  vars:
    tag: install

- name: Template Kibana config
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    mode: 0644
  notify:
    - Restart Kibana
  when: ansible_host in groups['kibana']
  vars:
    tag: configure
