---
- name: update Python and install PostgreSQL Python libraries
  apt:
    name:
      - python3-pexpect
      - python3-pip
      - python3-dev
      - python3-venv
      - python3-psycopg2
    state: present

- name: Install PostgreSQL
  apt:
    name:
      - "postgresql"
      - "postgresql-contrib"
    state: present
  become: true

- name: "Allow all users connect to all databases from all sources"
  postgresql_pg_hba:
    dest: "{{ postgresql_pg_hba_conf }}"
    contype: host
    users: all
    databases: all
    method: "{{ postgresql_password_encryption }}"
    source: "{{ item }}"
    keep_comments_at_rules: true
  with_items:
  - "::/0"
  - "0.0.0.0/0"
  become: true
  become_user: "{{ postgresql_user }}"
  vars:
    ansible_ssh_pipelining: true
  notify: Restart postgresql

- name: Create rails user, set MD5-hashed password, grant privs
  postgresql_user:
    name: zabbix
    password: "{{ vault_zabbix_password }}"
    role_attr_flags: CREATEDB,NOSUPERUSER
  vars:
    ansible_ssh_pipelining: true
  become: true
  become_user: "{{ postgresql_user }}"

- name: Ensure PostgreSQL databases are present
  community.postgresql.postgresql_db:
    name: "zabbix"
    lc_collate: "en_US.UTF-8"
    lc_ctype: "en_US.UTF-8"
    encoding: "UTF-8"
    owner: "zabbix"
    state: "present"
  become: true
  become_user: "{{ postgresql_user }}"
  vars:
    ansible_ssh_pipelining: true
