---
- name: Установка Nginx
  apt:
    name: nginx
    state: present
    update_cache: true

- name: Templates | Template HTML-page
  template:
    src: "index.html.j2"
    dest: "{{ html_page_folder }}/index.html"
    owner: "{{ mginx.user.name }}"
    group: "{{ nginx.user.group }}"
    mode: 0644
  notify:
    - Restart Nginx
