---
- name: Install elk stack
  hosts: all
  become: true
  roles:
  - role: roles/role_install_elastic
    when: tag == "install"

  - role: roles/role_install_kibana
    when: tag == "install"

  - role: roles/role_install_filebit
    when: tag == "install"