---
# tasks file for role_install_zabbix
- name: Install zabbix repo
  apt:
    deb: https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix-release/zabbix-release_6.0-5+debian12_all.deb

- name: Install zabbix
  apt:
    name:
     - zabbix-server-pgsql
     - zabbix-frontend-php
     - php8.2-pgsql
     - zabbix-nginx-conf
     - zabbix-sql-scripts
    state: present
    update_cache: true
  when: ansible_host in groups['zabbix']

- name: Run Zabbix SQL-script | Import schema and data to PostgreSQL
  shell:
    zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | sudo -u zabbix psql zabbix
  when: ansible_host in groups['zabbix']

- name: Настройка DBPassword в конфигурационном файле Zabbix
  lineinfile:
    path: /etc/zabbix/zabbix_server.conf
    regexp: '^#.?DBPassword='
    line: 'DBPassword=zabbix'
  when: ansible_host in groups['zabbix']
  
- name: Templates | Template nginx.conf
  template:
    src: "nginx.conf.j2"
    dest: "{{ zabbix_conf_dir }}/nginx.conf"
    mode: 0644
  notify: Restart Zabbix
  when: ansible_host in groups['zabbix']

- name: install Zabbix-agent
  apt:
   name: zabbix-agent
   state: present
   update_cache: true
  notify: Restart Zabbix-agent

- name: Create a directory for Zabbix logs
  file:
    path: /var/log/zabbix
    state: directory
    mode: '0755'

- name: Template Zabbix Agent config
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
  notify: Restart Zabbix-agent