---
- name: Install PostgreSQL Python libraries
  apt:
    name: "{{ postgresql_python_library }}"
    state: present

- name: Install PostgreSQL
  package:
    name:
      - "postgresql{{ postgresql_version }}"
      - "postgresql{{ postgresql_version }}-server"
      - "postgresql{{ postgresql_version }}-contrib"
    state: present
  become: true

- name: "Allow all users connect to all databases from all sources"
  postgresql_pg_hba:
    dest: "{{ postgresql_pg_hba_conf }}"
    contype: host
    users: all
    databases: all
    method: "{{ postgresql_password_encryption }}"
    source: "{{ item }}"
    keep_comments_at_rules: true
  with_items:
  - "::/0"
  - "0.0.0.0/0"
  become: true
  become_user: "{{ postgresql_user }}"
  vars:
    ansible_ssh_pipelining: true
  notify: Restart postgresql

- name: Create rails user, set MD5-hashed password, grant privs
  postgresql_user:
    name: zabbix
    password: "{{ vault_zabbix_password }}"
    role_attr_flags: CREATEDB,NOSUPERUSER

- name: Run Zabbix SQL-script | Import schema and data to PostgreSQL
  shell:
    zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | sudo -u zabbix psql zabbix

- name: Настройка DBPassword в конфигурационном файле Zabbix
  lineinfile:
    path: /etc/zabbix/zabbix_server.conf
    regexp: '^DBPassword='
    line: 'DBPassword=zabbix'
